const promptExamples = [
  'Friends planning a surprise birthday party for a mutual friend.',
  'Siblings discussing weekend hiking plans and gear recommendations.',
  'Colleagues troubleshooting a technical issue with a shared project.',
  'Team members coordinating a lunch and dietary preferences.',
  'Roommates debating the ending of a popular TV show.',
  'Couple sharing travel tips for an upcoming vacation destination.',
  "Coworkers brainstorming gift ideas for a colleague's farewell.",
  'Industry peers comparing notes on a recent conference.',
  'Neighbors organizing a community cleanup event.',
  'Friends discussing a new restaurant that opened nearby.',
  'Parents and their children solving a puzzle or riddle together.',
  'Gym buddies planning a group workout session.',
  'Book club members exchanging reading recommendations.',
  'Project team collaborating on a presentation deadline.',
  'Friends sharing home cooking experiments and recipes.',
  'Tech enthusiast friends discussing a new productivity app.',
  'College friends planning a virtual game night.',
  'Parents coordinating childcare arrangements for a playdate.',
  'Mentor and mentee sharing feedback on a creative project draft.',
  'Teacher and student planning an interactive field trip.',
  'Grandparent and grandchild plotting a treasure hunt.',
  'Friends troubleshooting a video game glitch together.',
  'Old friends planning a reunion road trip adventure.',
  'Siblings creating an elaborate birthday scavenger hunt.',
  'Fitness buddies challenging each other to a fun competition.',
  'Neighbors organizing a block-wide water balloon fight.',
  'Band members brainstorming outrageous stage costumes.',
  'Parent volunteers designing carnival games for a school festival.',
  'Newlyweds decorating their first home with themed rooms.',
  'Artist friends collaborating on a neighborhood mural.',
  'Long-distance couple planning surprise activities for their reunion.',
  'Study group members creating fun mnemonics for exam prep.',
  'Youth sports teammates inventing a new training game.',
  'Apartment neighbors planning a rooftop movie night.',
  'Cousins designing challenges for a family game day.',
  'New friends discovering shared obscure interests.',
  'Former classmates recreating iconic high school photos.',
  'Roommates hosting a themed dinner party competition.',
  'Travel buddies mapping out an adventure-filled itinerary.',
  'Parent and teenager designing a bedroom makeover.',
  'Volunteer friends brainstorming a flash mob performance.',
  'Friends planning outfits for a costume party.',
  'Hiking partners creating a bucket list of scenic trails.',
  'Childhood friends recreating childhood photos years later.',
  'Book club members designing literary-themed cocktails.',
  'Neighbors planning a community garden with whimsical elements.',
  'Theater friends practicing improvisation scenarios.',
  'Online gaming friends creating custom character backgrounds.',
  'In-laws competing in a holiday decoration contest.',
];

export default promptExamples;
