const CHAT_DATA_2 = [
  {
    name: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message: 'Hey, have you heard about that new horror movie Sinners that just came out?',
    time: '3:15 PM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
  {
    name: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: "OMG yes! I've been dying to see it. The reviews are saying it's the scariest movie of the year!",
    time: '3:17 PM',
    emojiReaction: 'exclamation',
    messagesInGroup: 2,
  },
  {
    name: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: 'Do you want to go see it this weekend?',
    time: '3:17 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message: "Definitely! I'm free Saturday night. How about you?",
    time: '3:20 PM',
    emojiReaction: 'thumbsUp',
    messagesInGroup: 2,
  },
  {
    name: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message: 'We could check out the 7:30 show at the Regal downtown',
    time: '3:21 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: 'Saturday at 7:30 works perfect for me! Should we grab dinner before?',
    time: '3:23 PM',
    emojiReaction: 'heart',
    messagesInGroup: 1,
  },
  {
    name: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message: 'Great idea! That Italian place next to the theater is pretty good. Wanna try that?',
    time: '3:25 PM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
  {
    name: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: "Perfect! Let's meet there at 5:30? That should give us plenty of time before the movie.",
    time: '3:28 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: "I heard the ending of Sinners is absolutely wild. I'm so excited!",
    time: '3:29 PM',
    emojiReaction: 'haha',
    messagesInGroup: 2,
  },
  {
    name: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message:
      "It's a date! 5:30 at Bella's and then Sinners at 7:30. I'll book the tickets online tonight so we don't have to worry about it selling out.",
    time: '3:32 PM',
    emojiReaction: 'exclamation',
    messagesInGroup: 1,
  },
] as const;

const CHAT_DATA_3 = [
  {
    name: 'Sarah Wilson',
    gender: 'female',
    role: 'sender',
    message: 'Hey team! Should we meet up for lunch tomorrow?',
    time: '11:30 AM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
  {
    name: 'David Park',
    gender: 'male',
    role: 'recipient',
    message: "I'm totally down! Been craving that new ramen place",
    time: '11:32 AM',
    emojiReaction: 'thumbsUp',
    messagesInGroup: 1,
  },
  {
    name: 'Emma Thompson',
    gender: 'female',
    role: 'recipient',
    message: 'Yesss ramen sounds amazing!',
    time: '11:33 AM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Emma Thompson',
    gender: 'female',
    role: 'recipient',
    message: 'What time works for everyone?',
    time: '11:33 AM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Sarah Wilson',
    gender: 'female',
    role: 'sender',
    message: 'How about 12:30? That gives us enough time',
    time: '11:35 AM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Sarah Wilson',
    gender: 'female',
    role: 'sender',
    message: 'I can make reservations if you want',
    time: '11:35 AM',
    emojiReaction: 'heart',
    messagesInGroup: 2,
  },
  {
    name: 'David Park',
    gender: 'male',
    role: 'recipient',
    message: '12:30 works perfectly for me',
    time: '11:37 AM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'David Park',
    gender: 'male',
    role: 'recipient',
    message: 'Thanks for making the reservation Sarah!',
    time: '11:37 AM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Emma Thompson',
    gender: 'female',
    role: 'recipient',
    message: 'Same here! See you both tomorrow at 12:30 🍜',
    time: '11:39 AM',
    emojiReaction: 'exclamation',
    messagesInGroup: 1,
  },
  {
    name: 'Sarah Wilson',
    gender: 'female',
    role: 'sender',
    message: "Great! Just booked a table for 3. Can't wait!",
    time: '11:42 AM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
] as const;

const CHAT_DATA_4 = [
  {
    name: 'Alex Rodriguez',
    gender: 'male',
    role: 'sender',
    message: 'Anyone up for game night this Friday?',
    time: '7:45 PM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
  {
    name: 'Jessica Liu',
    gender: 'female',
    role: 'recipient',
    message: 'Count me in! I can bring snacks',
    time: '7:47 PM',
    emojiReaction: 'thumbsUp',
    messagesInGroup: 1,
  },
  {
    name: 'Michael Brown',
    gender: 'male',
    role: 'recipient',
    message: "I'm down! Should we do board games or video games?",
    time: '7:48 PM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
  {
    name: 'Sophia Martinez',
    gender: 'female',
    role: 'recipient',
    message: 'Board games please! I just got Wingspan',
    time: '7:50 PM',
    emojiReaction: 'heart',
    messagesInGroup: 2,
  },
  {
    name: 'Sophia Martinez',
    gender: 'female',
    role: 'recipient',
    message: "It's supposed to be really fun",
    time: '7:50 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Alex Rodriguez',
    gender: 'male',
    role: 'sender',
    message: "Ooh I've been wanting to try that!",
    time: '7:52 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Alex Rodriguez',
    gender: 'male',
    role: 'sender',
    message: 'My place at 8pm work for everyone?',
    time: '7:52 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Jessica Liu',
    gender: 'female',
    role: 'recipient',
    message: 'Perfect! I can be there by 8',
    time: '7:54 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    name: 'Jessica Liu',
    gender: 'female',
    role: 'recipient',
    message: "I'll bring chips and dip",
    time: '7:54 PM',
    emojiReaction: 'exclamation',
    messagesInGroup: 2,
  },
  {
    name: 'Michael Brown',
    gender: 'male',
    role: 'recipient',
    message: '8pm works! I can bring drinks',
    time: '7:56 PM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
  {
    name: 'Sophia Martinez',
    gender: 'female',
    role: 'recipient',
    message: "See you all Friday! I'll bring Wingspan and maybe one other game",
    time: '7:58 PM',
    emojiReaction: 'haha',
    messagesInGroup: 1,
  },
  {
    name: 'Alex Rodriguez',
    gender: 'male',
    role: 'sender',
    message: "Awesome! It's a plan. Friday 8pm at my place for game night!",
    time: '8:00 PM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
] as const;

export { CHAT_DATA_2, CHAT_DATA_3, CHAT_DATA_4 };
export default CHAT_DATA_2;
