const chatData = [
  {
    participantName: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message: 'Hey, have you heard about that new horror movie Sinners that just came out?',
    time: '3:15 PM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
  {
    participantName: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: "OMG yes! I've been dying to see it. The reviews are saying it's the scariest movie of the year!",
    time: '3:17 PM',
    emojiReaction: 'exclamation',
    messagesInGroup: 2,
  },
  {
    participantName: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: 'Do you want to go see it this weekend?',
    time: '3:17 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    participantName: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message: "Definitely! I'm free Saturday night. How about you?",
    time: '3:20 PM',
    emojiReaction: 'thumbs up',
    messagesInGroup: 2,
  },
  {
    participantName: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message: 'We could check out the 7:30 show at the Regal downtown',
    time: '3:21 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    participantName: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: 'Saturday at 7:30 works perfect for me! Should we grab dinner before?',
    time: '3:23 PM',
    emojiReaction: 'heart',
    messagesInGroup: 1,
  },
  {
    participantName: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message: 'Great idea! That Italian place next to the theater is pretty good. Wanna try that?',
    time: '3:25 PM',
    emojiReaction: null,
    messagesInGroup: 1,
  },
  {
    participantName: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: "Perfect! Let's meet there at 5:30? That should give us plenty of time before the movie.",
    time: '3:28 PM',
    emojiReaction: null,
    messagesInGroup: 2,
  },
  {
    participantName: 'Amanda Chen',
    gender: 'female',
    role: 'recipient',
    message: "I heard the ending of Sinners is absolutely wild. I'm so excited!",
    time: '3:29 PM',
    emojiReaction: 'haha',
    messagesInGroup: 2,
  },
  {
    participantName: 'Mike Johnson',
    gender: 'male',
    role: 'sender',
    message:
      "It's a date! 5:30 at Bella's and then Sinners at 7:30. I'll book the tickets online tonight so we don't have to worry about it selling out.",
    time: '3:32 PM',
    emojiReaction: 'exclamation',
    messagesInGroup: 1,
  },
];

export default chatData;
