name: Lint and Format Check

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  javascript-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run style:write

      - name: Run ESLint
        run: npm run lint:fix

      - name: Run TypeScript type check
        run: npx tsc --noEmit --skipLibCheck

      - name: Run tests
        run: npm test -- --passWithNoTests
